# Elasticsearch stack designed for container-native deployment
# on Joyent's Triton platform.

# ---------------------------------------------------
# The master-only node serves as the coordinator of the cluster only

elasticsearch_master:
    extends:
      file: common-compose.yml
      service: elasticsearch
    environment:
    - ES_NODE_MASTER=true
    - ES_NODE_DATA=false
    - CONTAINERBUDDY=file:///etc/containerbuddy-master.json
    links:
    - consul:consul # we'll remove this once TCNS goes live

    # We expose 9200 to the Internet on the master only in this example for
    # illustration and testing.
    ports:
    - 9200 # REST API

# ---------------------------------------------------
# The default nodes store data and act as potential master nodes.

elasticsearch:
    extends:
      file: common-compose.yml
      service: elasticsearch
    links:
    - consul:consul # we'll remove this once TCNS goes live

# ---------------------------------------------------
# Data-only nodes never act as master nodes.

elasticsearch_data:
    extends:
      file: common-compose.yml
      service: elasticsearch
    environment:
    - ES_NODE_MASTER=false
    - ES_NODE_DATA=true
    links:
    - consul:consul # we'll remove this once TCNS goes live

# ---------------------------------------------------
# Consul as a service discovery tier

consul:
    extends:
      file: common-compose.yml
      service: consul
