# Local testing version of Elasticsearch stack designed for
# container-native deployment on Joyent's Triton platform.

elasticsearch_master:
    extends:
      file: common-compose.yml
      service: elasticsearch
    mem_limit: 512m
    build: .
    environment:
    - ES_NODE_MASTER=true
    - ES_NODE_DATA=false
    - CONTAINERBUDDY=file:///etc/containerbuddy-master.json
    links:
    - consul:consul
    expose:
    - 9200 # REST API
    - 9300 # transport API

elasticsearch:
    extends:
      file: common-compose.yml
      service: elasticsearch
    mem_limit: 512m
    build: .
    links:
    - consul:consul
    expose:
    - 9200 # REST API
    - 9300 # transport API

elasticsearch_data:
    extends:
      file: common-compose.yml
      service: elasticsearch
    mem_limit: 512m
    build: .
    environment:
    - ES_NODE_MASTER=false
    - ES_NODE_DATA=true
    links:
    - consul:consul
    expose:
    - 9200 # REST API
    - 9300 # transport API

consul:
    extends:
      file: common-compose.yml
      service: consul
